import CreateAccount from "./CreateAccount";
import Home2 from "./Home2";
import Login from "./Login";
import Verification from "./Verification";
import Spinner from "./Spinner";
import Splash from "./splash";
import Contacts from "./Contacts";
import Dev from "./Dev";
import Edit from "./Edit";
import Chats from "./Chats";
import { EditAbout } from "./EditPages";
// import { SettingAccount } from "./SettingPages";
import Setting from "./Setting";
import AnalyticsPage from "./AnalyticsPage";
import Share from "./Share";
import SignUp from "./SignUp";
import RegisterVerification from "./Verification/index2";
import ForgetPassword from "./ForgetPassword";

export { CreateAccount,ForgetPassword, Chats, Home2, Edit, EditAbout, Login, Verification, Spinner, Splash, Contacts, Dev, Setting, AnalyticsPage,RegisterVerification ,Share,SignUp};
