import CreateAccount from "./CreateAccount";
import Home from "./Home";
import Login from "./Login";
import Verification from "./Verification";
import Spinner from "./Spinner";
import Splash from "./splash";
import Contacts from "./Contacts";
import Dev from "./Dev";
import Edit from "./Edit";
import Chats from "./Chats";
import {EditAbout} from "./EditPages";
export { CreateAccount, Chats,Home,Edit,EditAbout, Login, Verification, Spinner, Splash, Contacts, Dev };
