import EditAbout from "./About";
import EditGallery from "./Gallery";
import EditGoogleMap from "./GoogleMap";
import EditVideos from "./Videos";
import EditSocials from "./Socials";
import EditLinks from "./Links";
import EditAiSetting from "./AiSetting";
import EditContactInfo from "./ContactInfo";
import EditFile from "./File";
export { EditAbout, EditGallery, EditGoogleMap,EditFile, EditVideos, EditSocials, EditLinks, EditAiSetting, EditContactInfo };
